name: eco_route
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.6.1
  flutter_map: ^8.1.1
  http: ^1.2.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  permission_handler: ^11.3.1
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splesh_screen_image.png
    - assets/images/logo.png

